import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';import {connect} from './cdp.mjs';
export const c=await connect(),p="app.plugins.plugins['md-palette']",dir='.artifacts/stage4',js=s=>c.evaluate(s),pause=ms=>new Promise(r=>setTimeout(r,ms));
export async function wait(s){for(let i=0;i<60;i++){if(await js(s))return;await pause(100)}throw Error('Timeout '+s)}
export async function point(selector,edge=false){return js(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)throw Error('Missing '+${JSON.stringify(selector)});e.scrollIntoView({block:'nearest'});const r=e.getBoundingClientRect();return{x:r.x+r.width*.65,y:${edge?'r.y+2':'r.y+r.height/2'}}})()`)}
export async function tap(pt,button='left',count=1,modifiers=0){await c.send('Input.dispatchMouseEvent',{type:'mouseMoved',...pt});await c.send('Input.dispatchMouseEvent',{type:'mousePressed',button,clickCount:count,modifiers,...pt});await c.send('Input.dispatchMouseEvent',{type:'mouseReleased',button,clickCount:count,modifiers,...pt});await pause(180)}
export async function click(s,button='left',count=1,modifiers=0){await tap(await point(s),button,count,modifiers)}
export async function textClick(selector,text){await tap(await js(`(()=>{const e=[...document.querySelectorAll(${JSON.stringify(selector)})].find(e=>e.textContent.trim()===${JSON.stringify(text)});if(!e)throw Error('Missing text '+${JSON.stringify(text)});const r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()`))}
export async function key(key,code=key,vk){await c.send('Input.dispatchKeyEvent',{type:'keyDown',key,code,windowsVirtualKeyCode:vk});await c.send('Input.dispatchKeyEvent',{type:'keyUp',key,code,windowsVirtualKeyCode:vk});await pause(150)}
export async function type(text){await c.send('Input.insertText',{text});await pause(250)}
export const file=(name,surface='folder')=>`[data-surface="${surface}"][data-key="f:Folder-Review/${name}"]`;
export const folder=(id,surface='folder')=>`[data-surface="${surface}"][data-key="d:${id}"]`;
export async function drag(from,to,{edge=false,cancel=false,forbidden=false}={}){
 await c.send('Input.setInterceptDrags',{enabled:true});c.dragEvents.length=0;const a=await point(from);await c.send('Input.dispatchMouseEvent',{type:'mouseMoved',...a});await c.send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...a});for(let i=1;i<=8;i++)await c.send('Input.dispatchMouseEvent',{type:'mouseMoved',button:'left',buttons:1,x:a.x+i*3,y:a.y+i*2});for(let i=0;i<30&&!c.dragEvents.length;i++)await pause(50);assert.ok(c.dragEvents.length,'native drag started');const data=c.dragEvents.at(-1).data,b=await point(to,edge);await c.send('Input.dispatchDragEvent',{type:'dragEnter',...b,data});await c.send('Input.dispatchDragEvent',{type:'dragOver',...b,data});await pause(100);assert.equal(await js(`!!document.querySelector('.mdp-folder-forbidden')`),forbidden);
 if(cancel){await key('Escape','Escape',27);await c.send('Input.dispatchDragEvent',{type:'dragCancel',...b,data});}else await c.send('Input.dispatchDragEvent',{type:'drop',...b,data});await c.send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...b});await c.send('Input.setInterceptDrags',{enabled:false});await pause(400);
}
export async function view(name){await click('.mdp-folder-toolbar button');await textClick('.menu-item-title',name)}
export async function sort(name){await click('[aria-label="Folder 정렬"]');await textClick('.menu-item-title',name)}
export async function create(name,target='.mdp-tree-root'){await click(target,'right');await textClick('.menu-item-title','새 가상 폴더 만들기');await type(name);await textClick('.modal button','저장');await wait(`!document.querySelector('.modal')`);return js(`${p}.folders.folders.find(f=>f.name===${JSON.stringify(name)}).id`)}
