import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';
import {c,p,js,pause,wait,point,tap,click,textClick,key,type} from './stage4-helpers.mjs';
const dir='.artifacts/stage7',checks=[],check=s=>{checks.push(s);console.log('PASS',s)},card=n=>`.mdp-card[data-path="Review/${n}"]`;
async function hover(selector){await c.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:10,y:90});await key('Escape','Escape',27);const pt=await point(selector);await c.send('Input.dispatchMouseEvent',{type:'mouseMoved',...pt});await pause(350);assert.equal(await js(`!!document.querySelector('.hover-popover')`),false);await c.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Control',code:'ControlLeft',modifiers:2,windowsVirtualKeyCode:17});await wait(`!!document.querySelector('.hover-popover')`);await c.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Control',code:'ControlLeft',modifiers:0,windowsVirtualKeyCode:17});await c.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:10,y:90});await key('Escape','Escape',27);await pause(350)}
async function reorder(cancel){await click(card('A.md'));await click(card('C.md'),'left',1,2);const before=await js(`${p}.cards.order`),selected=before.filter(x=>['Review/A.md','Review/C.md'].includes(x));await c.send('Input.setInterceptDrags',{enabled:true});c.dragEvents.length=0;const a=await point(card('A.md')+' .mdp-card-name');await c.send('Input.dispatchMouseEvent',{type:'mouseMoved',...a});await c.send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...a});for(let i=1;i<9;i++)await c.send('Input.dispatchMouseEvent',{type:'mouseMoved',button:'left',buttons:1,x:a.x+i*3,y:a.y+i*2});for(let i=0;i<30&&!c.dragEvents.length;i++)await pause(50);assert.ok(c.dragEvents.length);const data=c.dragEvents.at(-1).data,r=await js(`document.querySelector(${JSON.stringify(card('D.md'))}).getBoundingClientRect().toJSON()`),b={x:r.x+r.width/2,y:r.bottom-3};for(const type of ['dragEnter','dragOver'])await c.send('Input.dispatchDragEvent',{type,...b,data});await wait(`!!document.querySelector('.mdp-drop-overlay')`);if(cancel){await key('Escape','Escape',27);await c.send('Input.dispatchDragEvent',{type:'dragCancel',...b,data})}else await c.send('Input.dispatchDragEvent',{type:'drop',...b,data});await c.send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...b});await c.send('Input.setInterceptDrags',{enabled:false});await pause(250);const after=await js(`${p}.cards.order`);if(cancel)assert.deepEqual(after,before);else{assert.notDeepEqual(after,before);assert.deepEqual(after.filter(x=>selected.includes(x)),selected)}}
try{
 await key('Escape','Escape',27);
 await c.send('Emulation.setFocusEmulationEnabled',{enabled:true});await c.send('Emulation.setDeviceMetricsOverride',{width:1700,height:1100,deviceScaleFactor:1,mobile:false});await js(`${p}.cards.display='list';${p}.selectView('link','card');true`);await pause(200);
 const originals=await js(`Promise.all(['A.md','B.md','C.md','D.md'].map(async n=>[n,await app.vault.read(app.vault.getAbstractFileByPath('Review/'+n))]))`);
 await click(card('A.md'));await click(card('C.md'),'left',1,2);await click(card('A.md'),'right');await textClick('.menu-item-title','새 Label 만들기');await type('묶음 라벨');await textClick('.modal button','만들기');const id=await js(`${p}.cards.assignments['Review/A.md']`);assert.equal(await js(`${p}.cards.assignments['Review/C.md']`),id);assert.notEqual(await js(`${p}.cards.assignments['Review/D.md']`),id);check('multi-selected cards receive one label; unselected label unchanged');
 await textClick('.mdp-chip','묶음 라벨');assert.equal(await js(`document.querySelectorAll('.mdp-card').length`),2);await textClick('.mdp-chip','All');await textClick('.mdp-chip','MD');await textClick('.mdp-link-tabs button','Folder');assert.equal(await js(`${p}.cards.fileType`),'md');assert.equal(await js(`document.querySelectorAll('[data-key="f:Review/그림.svg"]').length`),0);await textClick('.mdp-link-tabs button','Card');await textClick('.mdp-chip','전체');check('label filter and shared Card/Folder file type filter');
 await textClick('.mdp-card-view button','라벨 관리…');await textClick('.mdp-label-list button','묶음 라벨 (2)');assert.equal(await js(`document.querySelectorAll('.mdp-label-member').length`),2);await textClick('.modal button','라벨 삭제');await textClick('.mdp-label-delete-confirm button','라벨만 삭제');await key('Escape','Escape',27);assert.equal(await js(`Object.values(${p}.cards.assignments).includes(${JSON.stringify(id)})`),false);check('label management lists both uses and deletes label only');
 await reorder(false);await reorder(true);check('multi-card reorder shows insertion marker, keeps relative order; Escape preserves order');
 await hover(card('D.md'));await textClick('.mdp-link-tabs button','Folder');await hover('[data-surface="tree"][data-key="f:Review/D.md"]');await textClick('.mdp-link-tabs button','Connections');await hover('.mdp-connection-row[data-path="Review/D.md"]');check('Ctrl hover native previews on Card, Folder Tree and Connections');
 assert.deepEqual(await js(`Promise.all(['A.md','B.md','C.md','D.md'].map(async n=>[n,await app.vault.read(app.vault.getAbstractFileByPath('Review/'+n))]))`),originals);check('labels, filters and reorder leave source Markdown unchanged');
 await js(`window.s7DetailOriginal={main:${p}.mainLeaf,subs:${p}.subGroups.slice(),last:${p}.subGroup};app.workspace.setActiveLeaf(${p}.mainLeaf,{focus:true});true`);
 await js(`(async()=>{const l=app.workspace.getLeaf('tab');await l.openFile(app.vault.getAbstractFileByPath('Review/Empty.md'));await ${p}.setMain(l);${p}.selectView('metadata');return true})()`);await wait(`document.querySelectorAll('.mdp-metadata-empty').length===5`);const before=await js(`(()=>{const a=[];app.workspace.iterateAllLeaves(l=>{a.push(l.id)});return a.sort()})()`);await js(`${p}.unsetMain().then(()=>true)`);assert.equal(await js(`!!document.querySelector('.mdp-metadata-search')`),false);assert.equal(await js(`document.querySelectorAll('.mdp-space-icon').length`),0);assert.deepEqual(await js(`(()=>{const a=[];app.workspace.iterateAllLeaves(l=>{a.push(l.id)});return a.sort()})()`),before);check('empty Metadata differs from no Main; unset clears icons and preserves all tabs');
 await js(`(async()=>{const o=s7DetailOriginal;await ${p}.setMain(o.main);${p}.subGroups=o.subs;${p}.subGroup=o.last;${p}.sync(false);${p}.selectView('link','card');return true})()`);
 await c.screenshot(dir+'/details.png');assert.equal(c.errors.length,0);await writeFile(dir+'/details-result.json',JSON.stringify({passed:true,checks},null,2));
}catch(e){await c.screenshot(dir+'/details-failure.png');await writeFile(dir+'/details-failure.json',JSON.stringify({checks,error:String(e)},null,2));throw e}finally{c.close()}
