import assert from 'node:assert/strict';
import {writeFile,readFile,cp} from 'node:fs/promises';
import {c,p,js,pause,wait,point,tap,click,key} from './stage4-helpers.mjs';
const dir='.artifacts/stage7',checks=[];
const check=s=>{checks.push(s);console.log('PASS',s)};
async function menu(t){await tap(await js(`(()=>{const e=[...document.querySelectorAll('.menu-item-title')].find(e=>e.textContent===${JSON.stringify(t)});if(!e)throw Error('Missing '+${JSON.stringify(t)});e.scrollIntoView({block:'nearest'});const r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()`))}
async function drop(selector,pt){await c.send('Input.setInterceptDrags',{enabled:true});c.dragEvents.length=0;const a=await point(selector);await c.send('Input.dispatchMouseEvent',{type:'mouseMoved',...a});await c.send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...a});for(let i=1;i<=9;i++)await c.send('Input.dispatchMouseEvent',{type:'mouseMoved',button:'left',buttons:1,x:a.x+i*4,y:a.y+i*2});for(let i=0;i<30&&!c.dragEvents.length;i++)await pause(50);assert.ok(c.dragEvents.length,'native drag started');const data=c.dragEvents.at(-1).data;for(const type of ['dragEnter','dragOver','drop'])await c.send('Input.dispatchDragEvent',{type,x:pt.x,y:pt.y,data});await c.send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,x:pt.x,y:pt.y});await c.send('Input.setInterceptDrags',{enabled:false});await pause(200)}
const value=()=>js('s7sub.view.editor.getValue()');
async function position(){return js(`(()=>{const e=s7sub.view.editor,o=e.getValue().indexOf('여기에 추가: ')+8;e.scrollIntoView({from:e.offsetToPos(o),to:e.offsetToPos(o)},true);const r=e.cm.coordsAtPos(o);return{x:r.left+1,y:(r.top+r.bottom)/2,offset:e.posToOffset(e.posAtCoords(r.left+1,(r.top+r.bottom)/2))}})()`)}
const fixture='# 재사용 대상\n\n여기에 추가: \n\n[^mdp-1]: 기존 각주\n';
async function reset(){await js(`(async()=>{await s7sub.openFile(app.vault.getAbstractFileByPath('Review/B.md'));await s7sub.setViewState({...s7sub.getViewState(),state:{...s7sub.getViewState().state,mode:'source',source:true}});await app.workspace.revealLeaf(s7sub);s7sub.view.editor.setValue(${JSON.stringify(fixture)});await s7sub.view.save();return true})()`);await pause(200)}
async function metadata(){await js(`${p}.metadataCollapsed=[];${p}.selectView('metadata');true`);await pause(150)}
async function insert(selector,choice,expected){if(typeof expected==='string')expected=expected.replaceAll('[[Main','[[Review/Main');const before=await value(),pt=await position();await drop(selector,pt);await menu(choice);await wait(`!${p}.reuseDrag.pending`);const after=typeof expected==='function'?expected(before,pt.offset):before.slice(0,pt.offset)+expected+before.slice(pt.offset);assert.equal(await value(),after);check(choice+' exact document position')}
try{
 await c.send('Emulation.setFocusEmulationEnabled',{enabled:true});
 await c.send('Emulation.setDeviceMetricsOverride',{width:1700,height:1100,deviceScaleFactor:1,mobile:false});
 await key('Escape','Escape',27);
 const vault=await js('app.vault.adapter.getBasePath()');await cp(vault,dir+'/before-reuse-backup-'+Date.now(),{recursive:true});
 await js(`window.s7sub=${p}.subGroups[0].children[0];window.s7canvas=${p}.subGroups[1].children[0];true`);
 for(const [choice,text]of [['링크 삽입','[[D]]'],['임베드 삽입','![[D]]'],['본문 Markdown 삽입','# D 자료\n\n재사용 본문\n']]){await reset();await js(`${p}.selectView('link','card');true`);await pause(150);await insert('.mdp-card[data-path="Review/D.md"] .mdp-card-name',choice,text)}
 for(const [selector,choice,text]of [['.mdp-meta-highlights','텍스트 삽입','강조 자료'],['.mdp-meta-footnotes','텍스트로 삽입','수정한 보충 설명\n두 번째 줄'],['.mdp-meta-links:last-child','주소 그대로 삽입','https://example.com/reference']]){await reset();await metadata();await insert(selector,choice,text)}
 for(const [selector,choice,text]of [['.mdp-meta-blocks','블록 링크 삽입','[[Main#^block]]'],['.mdp-meta-blocks','블록 임베드 삽입','![[Main#^block]]'],['.mdp-meta-highlights','출처 링크 포함 삽입','강조 자료\n\n출처: [[Main]]'],['.mdp-meta-links:last-child','제목이 있는 링크 삽입','[참고 사이트](<https://example.com/reference>)']]){await reset();await metadata();await insert(selector,choice,text)}
 await reset();await metadata();await insert('.mdp-meta-footnotes','실제 각주로 추가',(s,o)=>s.slice(0,o)+'[^mdp-2]'+s.slice(o)+'\n\n[^mdp-2]: 수정한 보충 설명\n    두 번째 줄\n');
 await js('s7sub.view.editor.focus();true');for(const type of ['keyDown','keyUp'])await c.send('Input.dispatchKeyEvent',{type,key:'z',code:'KeyZ',windowsVirtualKeyCode:90,modifiers:2});await pause(150);assert.equal(await value(),fixture);check('one Undo removes footnote reference and definition');
 await reset();await metadata();const before=await value();await drop('.mdp-meta-footnotes',await position());await menu('취소');assert.equal(await value(),before);check('cancel inserts nothing');
 await drop('.mdp-meta-footnotes',await position());await js(`window.s7save=s7sub.view.save;s7sub.view.save=async()=>{throw Error('Stage7 injected save failure')};true`);
 try{await menu('실제 각주로 추가');await wait(`!${p}.reuseDrag.pending`);assert.equal(await value(),before);assert.equal(await js('app.vault.read(s7sub.view.file)'),before)}finally{await js('s7sub.view.save=s7save;delete window.s7save;true')};check('save failure restores editor and disk');
 await drop('.mdp-meta-links:last-child',await position());await js(`s7sub.view.editor.replaceRange('새 편집 ',{line:0,ch:0});true`);await menu('주소 그대로 삽입');await wait(`!${p}.reuseDrag.pending`);assert.equal(await value(),'새 편집 '+before);check('intervening target edit cancels stale insertion');
 await js(`(async()=>{await s7sub.view.save();await s7canvas.openFile(app.vault.getAbstractFileByPath('Review/Board.canvas'));return true})()`);await pause(5500);await metadata();
 for(const [selector,choice,text]of [['.mdp-meta-highlights','텍스트 카드 만들기','강조 자료'],['.mdp-meta-highlights','출처 링크 포함 카드 만들기','강조 자료\n\n출처: [[Main]]'],['.mdp-meta-blocks','블록 내용 카드 만들기','블록 내용'],['.mdp-meta-blocks','블록 링크 카드 만들기','[[Main#^block]]'],['.mdp-meta-footnotes','텍스트 카드 만들기','수정한 보충 설명\n두 번째 줄'],['.mdp-meta-footnotes','각주 카드 만들기','[^mdp-1]\n\n[^mdp-1]: 수정한 보충 설명\n    두 번째 줄\n'],['.mdp-meta-links:last-child','주소 텍스트 카드 만들기','https://example.com/reference'],['.mdp-meta-links:last-child','제목 링크 카드 만들기','[참고 사이트](<https://example.com/reference>)']]){
  const ids=await js('[...s7canvas.view.canvas.nodes.keys()]');const pt=await js(`(()=>{const r=s7canvas.view.canvas.wrapperEl.getBoundingClientRect();return{x:r.x+r.width*.3,y:r.y+r.height*.4}})()`);await drop(selector,pt);await menu(choice);await wait(`!${p}.reuseDrag.pending`);const node=await js(`s7canvas.view.canvas.getData().nodes.find(n=>!${JSON.stringify(ids)}.includes(n.id))`);assert.equal(node.text,text.replaceAll('[[Main','[[Review/Main'));check(choice+' Canvas insertion');
 }
 const beforeCanvas=await js('JSON.stringify(s7canvas.view.canvas.getData())');await js(`${p}.selectView('link','card');true`);await pause(150);const pt=await js(`(()=>{const r=s7canvas.view.canvas.wrapperEl.getBoundingClientRect();return{x:r.x+r.width*.3,y:r.y+r.height*.4}})()`);await drop('.mdp-card[data-path="Review/D.md"] .mdp-card-name',pt);assert.equal(await js('JSON.stringify(s7canvas.view.canvas.getData())'),beforeCanvas);assert.equal(await js('!!document.querySelector(".menu")'),false);check('Card drop into Canvas rejected without changing nodes');
 assert.equal(await js(`app.vault.read(app.vault.getAbstractFileByPath('Review/D.md'))`),JSON.parse(await readFile(dir+'/fixtures.json','utf8'))['D.md']);check('reused source Markdown preserved');
 await js(`window.s7PreviousSub=s7sub;s7sub=${p}.mainLeaf;true`);const mainBefore=await value();
 try{await js(`${p}.selectView('link','card');true`);await pause(150);await insert('.mdp-card[data-path="Review/D.md"] .mdp-card-name','링크 삽입','[[D]]')}finally{await js(`s7sub.view.editor.setValue(${JSON.stringify(mainBefore)});s7sub.view.save().then(()=>true)`);await js('s7sub=s7PreviousSub;true')}
 await c.screenshot(dir+'/reuse.png');assert.equal(c.errors.length,0);await writeFile(dir+'/reuse-result.json',JSON.stringify({passed:true,checks},null,2));
}catch(e){await c.screenshot(dir+'/reuse-failure.png');await writeFile(dir+'/reuse-failure.json',JSON.stringify({checks,error:String(e),errors:c.errors},null,2));throw e}finally{c.close()}
